### ISSUE TITLE
vaadin-input doesn't work in Edge

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-input#10]
![](https://raw.githubusercontent.com/vaadin/vaadin-input/54a1230ce7c560e4bf3ef430b3ce06ca5d1aae96/test/visual/screens/vaadin-input/default/default/edge.png)

Related to #6

**Comment by manolo** [comment]
which version of Edge ? It works in mine 14

**Comment by limonte** [comment]
Fixed: https://github.com/vaadin/vaadin-input/pull/6/files#diff-d074be29a747b1411ffdbe1823217a3cR12
