### ISSUE TITLE
Not working in Edge

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-input#29]
The demo pages are not rendered.

Console has an error:
> Unable to get property 'cssText' of undefined or null reference: webcomponents-lite.js (5,42707)

**Comment by manolo** [comment]
Some extra info:
- The problem is not related to latest work, I have checked out first commits and still happens.
- It does not happen when running any visual example, but in demos. So it could be related to some changes in helpers.

**Comment by manolo** [comment]
It happens the same in vaadin-button. Actually the problem is in the https://github.com/vaadin/elements-demo-resources `common.html` inport
