### ISSUE TITLE
autofocus doesn't work in Linux/Firefox

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-input#9]
![](https://raw.githubusercontent.com/vaadin/vaadin-input/54a1230ce7c560e4bf3ef430b3ce06ca5d1aae96/test/visual/screens/vaadin-input/default/default/firefox.png)

Related to #6

**Comment by limonte** [comment]
http://stackoverflow.com/a/9956938/1331425

> Autofocus is only done before onload has fired; it's meant to be a declarative way of specifying focus on initial page load.

**Comment by manolo** [comment]
Is there anything that we want to do with this?  Or a nice solution ?

**Comment by manolo** [comment]
I meant without recurring to JS.  Anyway sent a PR that fixes this with a bit of JS.
